name: Deploy SimpleAPI Container App
on: 
  push:
    branches:
      - master 
    paths:
      - examples/deploy_simpleapi_container_app/trigger.txt
  workflow_dispatch:
env:
  RESOURCE_GROUP_NAME: "simpleapi-container-app-rg"
  CONTAINER_APP_NAME: "simpleapi-container-app"
  ACR_NAME: "simpleapiacr"
  LOCATION: "brazilsouth"

jobs: 
  create_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List Resource Groups 
        uses: azure/cli@v2 
        with:
          azcliversion: latest 
          inlineScript: |
            az group list --output table

      - name: Create Resource Group 
        uses: azure/cli@v2 
        with:
          azcliversion: latest 
          inlineScript: |
            # verify if the resource group already exists
            existing_rg=$(az group exists --name ${{ env.RESOURCE_GROUP_NAME }})
            if [ "$existing_rg" = "false" ]; then
              echo "Creating resource group: ${{ env.RESOURCE_GROUP_NAME }}"
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
            else
              echo "Resource group ${{ env.RESOURCE_GROUP_NAME }} already exists."
            fi

      - name: Create Azure Container Registry
        uses: azure/cli@v2 
        with: 
          azcliversion: latest 
          inlineScript: |
            # verify if the container registry already exists
            existing_acr=$(az acr list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --query "[?name=='${{ env.ACR_NAME }}'].name" -o tsv)
            if [ -z "$existing_acr" ]; then
              echo "Creating Azure Container Registry: ${{ env.ACR_NAME }}"
              az acr create --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.ACR_NAME }} --sku Basic
            else
              echo "Azure Container Registry ${{ env.ACR_NAME }} already exists."
            fi
