name: Deploy SimpleAPI Container App
on: 
  push:
    branches:
      - master 
    paths:
      - examples/deploy_simpleapi_container_app/trigger.txt
  workflow_dispatch:

jobs: 
  create_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List Resource Groups 
        uses: azure/cli@v2 
        with:
          azcliversion: latest 
          inlineScript: |
            az group list --output table