name: Iris App CI/CD
on:
  push:
    branches:
      - master
    paths:
      - 'irisapp/trigger.txt'
  workflow_dispatch:
env:
  RESOURCE_GROUP_NAME: "irisapp-rg"
  CONTAINER_APP_NAME: "irisapp"
  CONTAINER_APP_ENV_NAME: "irisapp-env"
  REGISTRY_SERVER: "docker.io"
  REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  LOCATION: "brazilsouth"
  IMAGE_NAME: "tests/simpleapi:latest"

jobs:
  create_azure_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
      
  create_azure_web_app:
    env:
      SERVICE_PLAN_NAME: "irisapp-service-plan"
    runs-on: ubuntu-latest
    needs: create_azure_resources
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Service plan
        run: |
          az appservice plan create --name ${{ env.SERVICE_PLAN_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --sku B1 --is-linux