name: Iris App CI/CD (2)
on:
  push:
    branches:
      - master
    paths:
      - 'irisapp2/trigger.txt'
  workflow_dispatch:
env:
  RESOURCE_GROUP_NAME: "irisapp2-rg"
  STORAGE_ACCOUNT_NAME: "irisapp2storagegs"
  STORAGE_CONTAINER_NAME: "irisapp2-containergs"
  COSMOS_DB_ACCOUNT_NAME: "irisapp2cosmosdbgs"
  CONTAINER_APP_NAME: "irisapp2gs"
  CONTAINER_APP_ENV_NAME: "irisapp2-env"
  REGISTRY_SERVER: "https://docker.io"
  REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  LOCATION: "brazilsouth"
  IMAGE_NAME: "gilsama/irisapp:latest"

jobs:
  create_azure_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # tasks for this cicd pipeline.
      # verify if the azure resource group exists, if not create it.
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          # Check if the resource group already exists
          existing_rg=$(az group list --query "[?name=='${{ env.RESOURCE_GROUP_NAME }}'].name" -o tsv)
          if [ -n "$existing_rg" ]; then
            echo "Resource group ${{ env.RESOURCE_GROUP_NAME }} already exists."
          else
            echo "Creating resource group: ${{ env.RESOURCE_GROUP_NAME }}"
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
